### PR TITLE
[master] KTEL-20-Refactor

### PR DESCRIPTION
**Pull request by kdamas93**
This change complements: https://github.com/2600hz/kazoo-teletype/pull/65
The purpose of this change is to remove unnecessary text in 2 templates:
**Desktop Webphone App Enabled**
**Welcome to Desktop App**
We should never have 2600Hz emails in any of our branding templates for whitelabeling purposes.
The ticket related to this change is the following:https://2600hz-commercial.atlassian.net/browse/KTEL-20

### CODE REVIEW

**Comment by nkarunarathne** [comment]
Looks good to me.

**Comment by wdhammika** [comment]
@kdamas93 I'm Just curious about whether it has any changes for `desktop_webphone_enabled.text` module.

**Comment by kdamas93** [comment]
> This change complements: #65

I'm just curious if you have any changes for the desktop_webphone_enabled.text module.
@wdhammika 
Yes, this change is complementary to: https://github.com/2600hz/kazoo-teletype/pull/65

**Comment by wdhammika** [comment]
Everything Looks good to me. 👍

**Pull request merged**
