### PR TITLE
Adding changes on welcome template

### PR DESCRIPTION
**Pull request by kdamas93**
https://github.com/2600hz/kazoo-core/pull/380
https://github.com/2600hz/kazoo-crossbar/pull/243

### CODE REVIEW

**Comment by icehess** [comment]
Correct related PR to fix preview in Branding app (for master branch): https://github.com/2600hz/kazoo-crossbar/pull/243 

the linked core pr is not related
the linked crossbar pr is for 5.0 not master branch.

**Comment by icehess** [comment]
@kdamas93 Does this needs to be back ported to 5.0?

**Comment by kdamas93** [comment]
> @kdamas93 Does this needs to be back ported to 5.0?

In the Jira ticket it mentions that it must be integrated to 5.0

**Comment by kdamas93** [comment]
> Correct related PR to fix preview in Branding app (for master branch): [2600hz/kazoo-crossbar#243](https://github.com/2600hz/kazoo-crossbar/pull/243)
> Yes, my bad, change done :)
> the linked core pr is not related the linked crossbar pr is for 5.0 not master branch.
Those changes came after running ci for the first time, do you want me to remove that pr ?

**Comment by kdamas93** [comment]
> @kdamas93 Does this needs to be back ported to 5.0?

This is the pr against 5.0 : https://github.com/2600hz/kazoo-teletype/pull/29

**Pull request merged**
